=== RoF555/dom4j/src/main/resources/user.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT users (user+)>

<!ELEMENT user (id,name,password,salary)>

<!--约束标签-->
<!--id,name,password 这三个标签都是字符串类型-->
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

<!--约束标签的属性-->
<!--
    user标签必须包含id属性，属性类型是ID，属性约束是#REQUIRED
    user标签必须包含country属性，属性类型是CDATA，属性约束是#IMPLIED
    user标签必须包含platfrom属性，属性类型是CDATA，属性约束是#FIXED
    user标签必须包含source属性，属性类型是枚举，默认值是Android
-->
<!ATTLIST user
        id ID #REQUIRED
        country CDATA #IMPLIED
        platfrom CDATA #FIXED "ittimeline"
        source (Android|IOS|WeChat) "Android"
        >

=== RoF555/dom4j/src/main/resources/user.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE users SYSTEM "user.dtd">
<users>
    <user id="TB10001" country="Chinese" source="Android">
        <id>10001</id>
        <name>admin</name>
        <password>111111</password>
        <salary><![CDATA[salary > 15000 & salary < 30000]]></salary>
    </user>

    <user id="TB10002" country="Chinese" source="IOS">
        <id>10002</id>
        <name>tony</name>
        <password>666666</password>
        <salary>
            <![CDATA[
                salary > 15000 & salary < 30000
            ]]>
        </salary>
    </user>
</users>
